name: webappfolio
description: .
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.1
  shared_preferences: ^2.2.0
  firebase_auth: ^4.8.0
  equatable: ^2.0.5
  dio: ^5.3.2
  get_it: ^7.6.0
  provider: ^6.0.5
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.5
  day_night_switcher: ^0.2.0+1
  url_launcher: ^6.1.12

dev_dependencies:
  animated_native_splash: ^1.3.0
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/private_policy.txt
    - assets/terms_of_use.txt
    - assets/avatar.png
    - assets/in_mind_logo.png
    - assets/google_fonts/
    - assets/google_play_img.png
    - assets/in_mind_logo_with_background.png
    - assets/in_mind_logo.png


animated_native_splash:

  # This package generates native code to customize Flutter's splash

  # jsonFile is the only required parameter.This the file use to setup the animation object.
  jsonFile: assets/splash.json

